package com.movies.models;

import java.util.Comparator;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Movies")
public class Movie  {
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String imdb_title_id;
	@DynamoDBAttribute
	private String title;
	@DynamoDBAttribute
	private String original_title;
	@DynamoDBAttribute
	private String year;
	@DynamoDBAttribute
	private String date_published;
	@DynamoDBAttribute
	private String genre;
	@DynamoDBAttribute
	private String duration;
	@DynamoDBAttribute
	private String country;
	@DynamoDBAttribute
	private String language;
	@DynamoDBAttribute
	private String director;
	@DynamoDBAttribute
	private String writer;
	@DynamoDBAttribute
	private String production_company;
	@DynamoDBAttribute
	private String actors;
	@DynamoDBAttribute
	private String description;
	@DynamoDBAttribute
	private String avg_vote;
	@DynamoDBAttribute
	private String votes;
	@DynamoDBAttribute
	private String budget;
	@DynamoDBAttribute
	private String usa_gross_income;
	@DynamoDBAttribute
	private String worlwide_gross_income;
	@DynamoDBAttribute
	private String metascore;
	@DynamoDBAttribute
	private Integer reviews_from_users;
	@DynamoDBAttribute
	private String reviews_from_critics;
	
	public String getImdb_title_id() {
		return imdb_title_id;
	}
	public void setImdb_title_id(String imdb_title_id) {
		this.imdb_title_id = imdb_title_id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getOriginal_title() {
		return original_title;
	}
	public void setOriginal_title(String original_title) {
		this.original_title = original_title;
	}
	public String getYear() {
		return year;
	}
	public void setYear(String year) {
		this.year = year;
	}
	public String getDate_published() {
		return date_published;
	}
	public void setDate_published(String date_published) {
		this.date_published = date_published;
	}
	public String getGenre() {
		return genre;
	}
	public void setGenre(String genre) {
		this.genre = genre;
	}
	public String getDuration() {
		return duration;
	}
	public void setDuration(String duration) {
		this.duration = duration;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getLanguage() {
		return language;
	}
	public void setLanguage(String language) {
		this.language = language;
	}
	public String getDirector() {
		return director;
	}
	public void setDirector(String director) {
		this.director = director;
	}
	public String getWriter() {
		return writer;
	}
	public void setWriter(String writer) {
		this.writer = writer;
	}
	public String getProduction_company() {
		return production_company;
	}
	public void setProduction_company(String production_company) {
		this.production_company = production_company;
	}
	public String getActors() {
		return actors;
	}
	public void setActors(String actors) {
		this.actors = actors;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getAvg_vote() {
		return avg_vote;
	}
	public void setAvg_vote(String avg_vote) {
		this.avg_vote = avg_vote;
	}
	public String getVotes() {
		return votes;
	}
	public void setVotes(String votes) {
		this.votes = votes;
	}
	public String getBudget() {
		return budget;
	}
	public void setBudget(String budget) {
		this.budget = budget;
	}
	public String getUsa_gross_income() {
		return usa_gross_income;
	}
	public void setUsa_gross_income(String usa_gross_income) {
		this.usa_gross_income = usa_gross_income;
	}
	public String getWorlwide_gross_income() {
		return worlwide_gross_income;
	}
	public void setWorlwide_gross_income(String worlwide_gross_income) {
		this.worlwide_gross_income = worlwide_gross_income;
	}
	public String getMetascore() {
		return metascore;
	}
	public void setMetascore(String metascore) {
		this.metascore = metascore;
	}
	public Integer getReviews_from_users() {
		return reviews_from_users;
	}
	public void setReviews_from_users(Integer reviews_from_users) {
		this.reviews_from_users = reviews_from_users;
	}
	public String getReviews_from_critics() {
		return reviews_from_critics;
	}
	public void setReviews_from_critics(String reviews_from_critics) {
		this.reviews_from_critics = reviews_from_critics;
	}
	public Movie() {}
	public Movie(String imdb_title_id, String title, String original_title, String year, String date_published,
			String genre, String duration, String country, String language, String director, String writer,
			String production_company, String actors, String description, String avg_vote, String votes, String budget,
			String usa_gross_income, String worlwide_gross_income, String metascore, Integer reviews_from_users,
			String reviews_from_critics) {
		super();
		this.imdb_title_id = imdb_title_id;
		this.title = title;
		this.original_title = original_title;
		this.year = year;
		this.date_published = date_published;
		this.genre = genre;
		this.duration = duration;
		this.country = country;
		this.language = language;
		this.director = director;
		this.writer = writer;
		this.production_company = production_company;
		this.actors = actors;
		this.description = description;
		this.avg_vote = avg_vote;
		this.votes = votes;
		this.budget = budget;
		this.usa_gross_income = usa_gross_income;
		this.worlwide_gross_income = worlwide_gross_income;
		this.metascore = metascore;
		this.reviews_from_users = reviews_from_users;
		this.reviews_from_critics = reviews_from_critics;
	}
	@Override
	public String toString() {
		return "Movie [imdb_title_id=" + imdb_title_id + ", title=" + title + ", original_title=" + original_title
				+ ", year=" + year + ", date_published=" + date_published + ", genre=" + genre + ", duration="
				+ duration + ", country=" + country + ", language=" + language + ", director=" + director + ", writer="
				+ writer + ", production_company=" + production_company + ", actors=" + actors + ", description="
				+ description + ", avg_vote=" + avg_vote + ", votes=" + votes + ", budget=" + budget
				+ ", usa_gross_income=" + usa_gross_income + ", worlwide_gross_income=" + worlwide_gross_income
				+ ", metascore=" + metascore + ", reviews_from_users=" + reviews_from_users + ", reviews_from_critics="
				+ reviews_from_critics + "]";
	}
	   public static class OrderByReviews implements Comparator<Movie> {

			@Override
			public int compare(Movie o1, Movie o2) {
				return o2.getReviews_from_users()-o1.getReviews_from_users();
			}
	    }
	
}

